name: Deploy
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 * * * *'  # Every hour
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
        id: pages
    outputs:
      base_url: ${{ steps.pages.outputs.base_url }}
  build:
    needs: pages
    uses: ./.github/workflows/build.yml
    with:
      site_repo: binodil/blog
      site_ref: main
      theme_repo: pelican-themes/sidecar
      theme_ref: main
      base_url: ${{ needs.pages.outputs.base_url }}
      artifact_name: "github-pages"
    secrets:
      site_repo_token: ${{ secrets.BLOG_TOKEN3 }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
